### ISSUE TITLE
Add contact form

### ISSUE THREAD

**Issue by karin112358** [coding-club-linz/rust-linz#21]
Add new section (white) with a contact form below participation. The contact form should be similar to https://linz.coderdojo.net/ (use English labels).

![image](https://user-images.githubusercontent.com/9429286/87229305-47d02700-c3a7-11ea-8c60-8ec7c8ad96a9.png)

The same JavaScript function like in https://linz.coderdojo.net/ with the same web service url can be used.

- [] submit does not work
- [] add menu item

**Comment by rstropek** [comment]
Send message using a HTTP `POST` to a URL that you can get from @rstropek. The content should be as follows:

```json
{
    "email": "somebody@somwhere.com",
    "text": "this is\na test\nGreetings",
    "source": "rust"
}
```

The difference to the CoderDojo website is the parameter `source`. If it is `rust`, the workflow will send the message to the Rust distribution list. Otherwise, to the CoderDojo distribution list.
